/*
Copyright 2022 The OpenFunction Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ClusterEventBusListerExpansion allows custom methods to be added to
// ClusterEventBusLister.
type ClusterEventBusListerExpansion interface{}

// ClusterEventBusNamespaceListerExpansion allows custom methods to be added to
// ClusterEventBusNamespaceLister.
type ClusterEventBusNamespaceListerExpansion interface{}

// EventBusListerExpansion allows custom methods to be added to
// EventBusLister.
type EventBusListerExpansion interface{}

// EventBusNamespaceListerExpansion allows custom methods to be added to
// EventBusNamespaceLister.
type EventBusNamespaceListerExpansion interface{}

// EventSourceListerExpansion allows custom methods to be added to
// EventSourceLister.
type EventSourceListerExpansion interface{}

// EventSourceNamespaceListerExpansion allows custom methods to be added to
// EventSourceNamespaceLister.
type EventSourceNamespaceListerExpansion interface{}

// TriggerListerExpansion allows custom methods to be added to
// TriggerLister.
type TriggerListerExpansion interface{}

// TriggerNamespaceListerExpansion allows custom methods to be added to
// TriggerNamespaceLister.
type TriggerNamespaceListerExpansion interface{}
