apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: faas-redis-pubsub
spec:
  metadata:
    - name: redisType
      value: cluster
    - name: redisHost
      value: drc-example-distributedrediscluster-0-0.example-distributedrediscluster-0.lowcode:6379,drc-example-distributedrediscluster-1-0.example-distri    butedrediscluster-1.lowcode:6379,drc-example-distributedrediscluster-2-0.example-distributedrediscluster-2.lowcode:6379
    - name: authRequired
      value: "true"
    - name: redisPassword
      value: qxp1234
    - name: maxMessageBytes
      value: 1024
  type: pubsub.redis
  version: v1