// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/v1alpha1/api.proto

package v1alpha1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateReq struct {
	ObjectMeta           *ObjectMeta `protobuf:"bytes,1,opt,name=objectMeta,proto3" json:"objectMeta,omitempty"`
	State                *Status     `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateReq) Reset()         { *m = CreateReq{} }
func (m *CreateReq) String() string { return proto.CompactTextString(m) }
func (*CreateReq) ProtoMessage()    {}
func (*CreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6db26900272f6875, []int{0}
}

func (m *CreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReq.Unmarshal(m, b)
}
func (m *CreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReq.Marshal(b, m, deterministic)
}
func (m *CreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReq.Merge(m, src)
}
func (m *CreateReq) XXX_Size() int {
	return xxx_messageInfo_CreateReq.Size(m)
}
func (m *CreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReq proto.InternalMessageInfo

func (m *CreateReq) GetObjectMeta() *ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

func (m *CreateReq) GetState() *Status {
	if m != nil {
		return m.State
	}
	return nil
}

type ObjectMeta struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namepsace            string            `protobuf:"bytes,2,opt,name=namepsace,proto3" json:"namepsace,omitempty"`
	Uid                  string            `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	CreationTime         string            `protobuf:"bytes,4,opt,name=creationTime,proto3" json:"creationTime,omitempty"`
	Labels               map[string]string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	OwnerReference       []*OwnerReference `protobuf:"bytes,6,rep,name=ownerReference,proto3" json:"ownerReference,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ObjectMeta) Reset()         { *m = ObjectMeta{} }
func (m *ObjectMeta) String() string { return proto.CompactTextString(m) }
func (*ObjectMeta) ProtoMessage()    {}
func (*ObjectMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_6db26900272f6875, []int{1}
}

func (m *ObjectMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectMeta.Unmarshal(m, b)
}
func (m *ObjectMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectMeta.Marshal(b, m, deterministic)
}
func (m *ObjectMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectMeta.Merge(m, src)
}
func (m *ObjectMeta) XXX_Size() int {
	return xxx_messageInfo_ObjectMeta.Size(m)
}
func (m *ObjectMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectMeta.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectMeta proto.InternalMessageInfo

func (m *ObjectMeta) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ObjectMeta) GetNamepsace() string {
	if m != nil {
		return m.Namepsace
	}
	return ""
}

func (m *ObjectMeta) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ObjectMeta) GetCreationTime() string {
	if m != nil {
		return m.CreationTime
	}
	return ""
}

func (m *ObjectMeta) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *ObjectMeta) GetOwnerReference() []*OwnerReference {
	if m != nil {
		return m.OwnerReference
	}
	return nil
}

type OwnerReference struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OwnerReference) Reset()         { *m = OwnerReference{} }
func (m *OwnerReference) String() string { return proto.CompactTextString(m) }
func (*OwnerReference) ProtoMessage()    {}
func (*OwnerReference) Descriptor() ([]byte, []int) {
	return fileDescriptor_6db26900272f6875, []int{2}
}

func (m *OwnerReference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OwnerReference.Unmarshal(m, b)
}
func (m *OwnerReference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OwnerReference.Marshal(b, m, deterministic)
}
func (m *OwnerReference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OwnerReference.Merge(m, src)
}
func (m *OwnerReference) XXX_Size() int {
	return xxx_messageInfo_OwnerReference.Size(m)
}
func (m *OwnerReference) XXX_DiscardUnknown() {
	xxx_messageInfo_OwnerReference.DiscardUnknown(m)
}

var xxx_messageInfo_OwnerReference proto.InternalMessageInfo

func (m *OwnerReference) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OwnerReference) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type Status struct {
	Status               string                   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ResourceRef          map[string]*RefCondition `protobuf:"bytes,2,rep,name=resourceRef,proto3" json:"resourceRef,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CompletionTime       string                   `protobuf:"bytes,3,opt,name=completionTime,proto3" json:"completionTime,omitempty"`
	PipelineRun          *PipelineRun             `protobuf:"bytes,4,opt,name=pipelineRun,proto3" json:"pipelineRun,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_6db26900272f6875, []int{3}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Status) GetResourceRef() map[string]*RefCondition {
	if m != nil {
		return m.ResourceRef
	}
	return nil
}

func (m *Status) GetCompletionTime() string {
	if m != nil {
		return m.CompletionTime
	}
	return ""
}

func (m *Status) GetPipelineRun() *PipelineRun {
	if m != nil {
		return m.PipelineRun
	}
	return nil
}

type RefCondition struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Conditions           []*Condition `protobuf:"bytes,2,rep,name=conditions,proto3" json:"conditions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RefCondition) Reset()         { *m = RefCondition{} }
func (m *RefCondition) String() string { return proto.CompactTextString(m) }
func (*RefCondition) ProtoMessage()    {}
func (*RefCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_6db26900272f6875, []int{4}
}

func (m *RefCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefCondition.Unmarshal(m, b)
}
func (m *RefCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefCondition.Marshal(b, m, deterministic)
}
func (m *RefCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefCondition.Merge(m, src)
}
func (m *RefCondition) XXX_Size() int {
	return xxx_messageInfo_RefCondition.Size(m)
}
func (m *RefCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_RefCondition.DiscardUnknown(m)
}

var xxx_messageInfo_RefCondition proto.InternalMessageInfo

func (m *RefCondition) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RefCondition) GetConditions() []*Condition {
	if m != nil {
		return m.Conditions
	}
	return nil
}

type Condition struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	LastTransitionTime   string   `protobuf:"bytes,4,opt,name=lastTransitionTime,proto3" json:"lastTransitionTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Condition) Reset()         { *m = Condition{} }
func (m *Condition) String() string { return proto.CompactTextString(m) }
func (*Condition) ProtoMessage()    {}
func (*Condition) Descriptor() ([]byte, []int) {
	return fileDescriptor_6db26900272f6875, []int{5}
}

func (m *Condition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Condition.Unmarshal(m, b)
}
func (m *Condition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Condition.Marshal(b, m, deterministic)
}
func (m *Condition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Condition.Merge(m, src)
}
func (m *Condition) XXX_Size() int {
	return xxx_messageInfo_Condition.Size(m)
}
func (m *Condition) XXX_DiscardUnknown() {
	xxx_messageInfo_Condition.DiscardUnknown(m)
}

var xxx_messageInfo_Condition proto.InternalMessageInfo

func (m *Condition) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Condition) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *Condition) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Condition) GetLastTransitionTime() string {
	if m != nil {
		return m.LastTransitionTime
	}
	return ""
}

type PipelineRun struct {
	Status               string     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	TaskRun              []*TaskRun `protobuf:"bytes,2,rep,name=taskRun,proto3" json:"taskRun,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PipelineRun) Reset()         { *m = PipelineRun{} }
func (m *PipelineRun) String() string { return proto.CompactTextString(m) }
func (*PipelineRun) ProtoMessage()    {}
func (*PipelineRun) Descriptor() ([]byte, []int) {
	return fileDescriptor_6db26900272f6875, []int{6}
}

func (m *PipelineRun) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PipelineRun.Unmarshal(m, b)
}
func (m *PipelineRun) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PipelineRun.Marshal(b, m, deterministic)
}
func (m *PipelineRun) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PipelineRun.Merge(m, src)
}
func (m *PipelineRun) XXX_Size() int {
	return xxx_messageInfo_PipelineRun.Size(m)
}
func (m *PipelineRun) XXX_DiscardUnknown() {
	xxx_messageInfo_PipelineRun.DiscardUnknown(m)
}

var xxx_messageInfo_PipelineRun proto.InternalMessageInfo

func (m *PipelineRun) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *PipelineRun) GetTaskRun() []*TaskRun {
	if m != nil {
		return m.TaskRun
	}
	return nil
}

type TaskRun struct {
	TaskName             string   `protobuf:"bytes,1,opt,name=taskName,proto3" json:"taskName,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	StartTime            string   `protobuf:"bytes,3,opt,name=startTime,proto3" json:"startTime,omitempty"`
	CompletionTime       string   `protobuf:"bytes,4,opt,name=completionTime,proto3" json:"completionTime,omitempty"`
	Step                 []*Step  `protobuf:"bytes,5,rep,name=step,proto3" json:"step,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskRun) Reset()         { *m = TaskRun{} }
func (m *TaskRun) String() string { return proto.CompactTextString(m) }
func (*TaskRun) ProtoMessage()    {}
func (*TaskRun) Descriptor() ([]byte, []int) {
	return fileDescriptor_6db26900272f6875, []int{7}
}

func (m *TaskRun) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskRun.Unmarshal(m, b)
}
func (m *TaskRun) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskRun.Marshal(b, m, deterministic)
}
func (m *TaskRun) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskRun.Merge(m, src)
}
func (m *TaskRun) XXX_Size() int {
	return xxx_messageInfo_TaskRun.Size(m)
}
func (m *TaskRun) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskRun.DiscardUnknown(m)
}

var xxx_messageInfo_TaskRun proto.InternalMessageInfo

func (m *TaskRun) GetTaskName() string {
	if m != nil {
		return m.TaskName
	}
	return ""
}

func (m *TaskRun) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *TaskRun) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *TaskRun) GetCompletionTime() string {
	if m != nil {
		return m.CompletionTime
	}
	return ""
}

func (m *TaskRun) GetStep() []*Step {
	if m != nil {
		return m.Step
	}
	return nil
}

type Step struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	StartTime            string   `protobuf:"bytes,2,opt,name=startTime,proto3" json:"startTime,omitempty"`
	CompletionTime       string   `protobuf:"bytes,3,opt,name=completionTime,proto3" json:"completionTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Step) Reset()         { *m = Step{} }
func (m *Step) String() string { return proto.CompactTextString(m) }
func (*Step) ProtoMessage()    {}
func (*Step) Descriptor() ([]byte, []int) {
	return fileDescriptor_6db26900272f6875, []int{8}
}

func (m *Step) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Step.Unmarshal(m, b)
}
func (m *Step) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Step.Marshal(b, m, deterministic)
}
func (m *Step) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Step.Merge(m, src)
}
func (m *Step) XXX_Size() int {
	return xxx_messageInfo_Step.Size(m)
}
func (m *Step) XXX_DiscardUnknown() {
	xxx_messageInfo_Step.DiscardUnknown(m)
}

var xxx_messageInfo_Step proto.InternalMessageInfo

func (m *Step) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Step) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *Step) GetCompletionTime() string {
	if m != nil {
		return m.CompletionTime
	}
	return ""
}

type UpdateReq struct {
	ObjectMeta           *ObjectMeta `protobuf:"bytes,1,opt,name=objectMeta,proto3" json:"objectMeta,omitempty"`
	State                *Status     `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateReq) Reset()         { *m = UpdateReq{} }
func (m *UpdateReq) String() string { return proto.CompactTextString(m) }
func (*UpdateReq) ProtoMessage()    {}
func (*UpdateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6db26900272f6875, []int{9}
}

func (m *UpdateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateReq.Unmarshal(m, b)
}
func (m *UpdateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateReq.Marshal(b, m, deterministic)
}
func (m *UpdateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateReq.Merge(m, src)
}
func (m *UpdateReq) XXX_Size() int {
	return xxx_messageInfo_UpdateReq.Size(m)
}
func (m *UpdateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateReq proto.InternalMessageInfo

func (m *UpdateReq) GetObjectMeta() *ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

func (m *UpdateReq) GetState() *Status {
	if m != nil {
		return m.State
	}
	return nil
}

type DeleteReq struct {
	ObjectMeta           *ObjectMeta `protobuf:"bytes,1,opt,name=objectMeta,proto3" json:"objectMeta,omitempty"`
	State                *Status     `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DeleteReq) Reset()         { *m = DeleteReq{} }
func (m *DeleteReq) String() string { return proto.CompactTextString(m) }
func (*DeleteReq) ProtoMessage()    {}
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6db26900272f6875, []int{10}
}

func (m *DeleteReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReq.Unmarshal(m, b)
}
func (m *DeleteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReq.Marshal(b, m, deterministic)
}
func (m *DeleteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReq.Merge(m, src)
}
func (m *DeleteReq) XXX_Size() int {
	return xxx_messageInfo_DeleteReq.Size(m)
}
func (m *DeleteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReq proto.InternalMessageInfo

func (m *DeleteReq) GetObjectMeta() *ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

func (m *DeleteReq) GetState() *Status {
	if m != nil {
		return m.State
	}
	return nil
}

type Resp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resp) Reset()         { *m = Resp{} }
func (m *Resp) String() string { return proto.CompactTextString(m) }
func (*Resp) ProtoMessage()    {}
func (*Resp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6db26900272f6875, []int{11}
}

func (m *Resp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resp.Unmarshal(m, b)
}
func (m *Resp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resp.Marshal(b, m, deterministic)
}
func (m *Resp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resp.Merge(m, src)
}
func (m *Resp) XXX_Size() int {
	return xxx_messageInfo_Resp.Size(m)
}
func (m *Resp) XXX_DiscardUnknown() {
	xxx_messageInfo_Resp.DiscardUnknown(m)
}

var xxx_messageInfo_Resp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateReq)(nil), "v1alpha1.CreateReq")
	proto.RegisterType((*ObjectMeta)(nil), "v1alpha1.ObjectMeta")
	proto.RegisterMapType((map[string]string)(nil), "v1alpha1.ObjectMeta.LabelsEntry")
	proto.RegisterType((*OwnerReference)(nil), "v1alpha1.OwnerReference")
	proto.RegisterType((*Status)(nil), "v1alpha1.Status")
	proto.RegisterMapType((map[string]*RefCondition)(nil), "v1alpha1.Status.ResourceRefEntry")
	proto.RegisterType((*RefCondition)(nil), "v1alpha1.RefCondition")
	proto.RegisterType((*Condition)(nil), "v1alpha1.Condition")
	proto.RegisterType((*PipelineRun)(nil), "v1alpha1.PipelineRun")
	proto.RegisterType((*TaskRun)(nil), "v1alpha1.TaskRun")
	proto.RegisterType((*Step)(nil), "v1alpha1.Step")
	proto.RegisterType((*UpdateReq)(nil), "v1alpha1.UpdateReq")
	proto.RegisterType((*DeleteReq)(nil), "v1alpha1.DeleteReq")
	proto.RegisterType((*Resp)(nil), "v1alpha1.Resp")
}

func init() { proto.RegisterFile("proto/v1alpha1/api.proto", fileDescriptor_6db26900272f6875) }

var fileDescriptor_6db26900272f6875 = []byte{
	// 627 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xcd, 0x6e, 0xd4, 0x30,
	0x10, 0x56, 0xd2, 0x34, 0xdb, 0x4c, 0xaa, 0x55, 0x31, 0xa5, 0x8a, 0x56, 0x3d, 0x94, 0x1c, 0xaa,
	0x4a, 0x40, 0xaa, 0x6e, 0x11, 0x14, 0x4e, 0x48, 0x0b, 0x07, 0x24, 0xfe, 0x64, 0x16, 0xb8, 0xe2,
	0xcd, 0xce, 0x42, 0x68, 0x36, 0x31, 0xb1, 0xb7, 0xa8, 0x0f, 0xc0, 0x2b, 0x70, 0xe4, 0xca, 0x81,
	0x97, 0x44, 0x71, 0x7e, 0xec, 0x8d, 0xb2, 0xe2, 0xd6, 0x53, 0x3c, 0x33, 0x9f, 0x3f, 0xcf, 0x7c,
	0x33, 0xb1, 0x21, 0xe0, 0x45, 0x2e, 0xf3, 0xd3, 0xab, 0x33, 0x96, 0xf2, 0xaf, 0xec, 0xec, 0x94,
	0xf1, 0x24, 0x52, 0x2e, 0xb2, 0xd3, 0xf8, 0xc2, 0x04, 0xbc, 0x49, 0x81, 0x4c, 0x22, 0xc5, 0xef,
	0xe4, 0x21, 0x40, 0x3e, 0xfb, 0x86, 0xb1, 0x7c, 0x8d, 0x92, 0x05, 0xd6, 0x91, 0x75, 0xe2, 0x8f,
	0xf7, 0xa3, 0x06, 0x1b, 0xbd, 0x6d, 0x63, 0xd4, 0xc0, 0x91, 0x63, 0xd8, 0x16, 0x92, 0x49, 0x0c,
	0x6c, 0xb5, 0x61, 0x4f, 0x6f, 0x78, 0x2f, 0x99, 0x5c, 0x09, 0x5a, 0x85, 0xc3, 0xbf, 0x36, 0x80,
	0xa6, 0x20, 0x04, 0x9c, 0x8c, 0x2d, 0x51, 0x1d, 0xe3, 0x51, 0xb5, 0x26, 0x87, 0xe0, 0x95, 0x5f,
	0x2e, 0x58, 0x5c, 0xd1, 0x79, 0x54, 0x3b, 0xc8, 0x1e, 0x6c, 0xad, 0x92, 0x79, 0xb0, 0xa5, 0xfc,
	0xe5, 0x92, 0x84, 0xb0, 0x1b, 0x97, 0xd9, 0x27, 0x79, 0x36, 0x4d, 0x96, 0x18, 0x38, 0x2a, 0xb4,
	0xe6, 0x23, 0x17, 0xe0, 0xa6, 0x6c, 0x86, 0xa9, 0x08, 0xb6, 0x8f, 0xb6, 0x4e, 0xfc, 0xf1, 0x51,
	0x5f, 0x41, 0xd1, 0x2b, 0x05, 0x79, 0x91, 0xc9, 0xe2, 0x9a, 0xd6, 0x78, 0xf2, 0x0c, 0x86, 0xf9,
	0x8f, 0x0c, 0x0b, 0x8a, 0x0b, 0x2c, 0x30, 0x8b, 0x31, 0x70, 0x15, 0x43, 0x60, 0x30, 0xac, 0xc5,
	0x69, 0x07, 0x3f, 0x7a, 0x02, 0xbe, 0x41, 0x5c, 0x16, 0x70, 0x89, 0xd7, 0x75, 0xc5, 0xe5, 0x92,
	0xec, 0xc3, 0xf6, 0x15, 0x4b, 0x57, 0x4d, 0xb1, 0x95, 0xf1, 0xd4, 0xbe, 0xb0, 0xc2, 0x47, 0x30,
	0x5c, 0x27, 0xef, 0x15, 0xac, 0x96, 0xc4, 0x6e, 0x25, 0x09, 0x7f, 0xdb, 0xe0, 0x56, 0xba, 0x93,
	0x03, 0x70, 0x85, 0x5a, 0xd5, 0x5b, 0x6a, 0x8b, 0x4c, 0xc0, 0x2f, 0x50, 0xe4, 0xab, 0x22, 0x46,
	0x8a, 0x8b, 0xc0, 0x56, 0x45, 0xdd, 0xed, 0xb6, 0x2d, 0xa2, 0x1a, 0x53, 0xe9, 0x62, 0xee, 0x22,
	0xc7, 0x30, 0x8c, 0xf3, 0x25, 0x4f, 0xb1, 0x15, 0xbf, 0xea, 0x4b, 0xc7, 0x4b, 0x1e, 0x83, 0xcf,
	0x13, 0x8e, 0x69, 0x92, 0x21, 0x5d, 0x65, 0xaa, 0x43, 0xfe, 0xf8, 0x8e, 0x3e, 0xec, 0x9d, 0x0e,
	0x52, 0x13, 0x39, 0xfa, 0x08, 0x7b, 0xdd, 0x0c, 0x7a, 0x04, 0xbc, 0x6f, 0x0a, 0xe8, 0x8f, 0x0f,
	0x34, 0x31, 0xc5, 0xc5, 0x24, 0xcf, 0xe6, 0x49, 0x99, 0x89, 0x29, 0xec, 0x27, 0xd8, 0x35, 0x43,
	0xbd, 0xb2, 0x9e, 0x03, 0xc4, 0x0d, 0x40, 0xd4, 0x02, 0xdd, 0xd6, 0xd4, 0x9a, 0xd7, 0x80, 0x85,
	0x3f, 0x2d, 0xf0, 0x34, 0xed, 0x26, 0xf1, 0x0f, 0xc0, 0x2d, 0x90, 0x89, 0x3c, 0xab, 0x9b, 0x56,
	0x5b, 0x24, 0x80, 0xc1, 0x12, 0x85, 0x60, 0x5f, 0x1a, 0x21, 0x1b, 0x93, 0x44, 0x40, 0x52, 0x26,
	0xe4, 0xb4, 0x60, 0x99, 0x48, 0x3a, 0xa3, 0xde, 0x13, 0x09, 0x29, 0xf8, 0x86, 0xa8, 0x1b, 0x13,
	0xb9, 0x07, 0x03, 0xc9, 0xc4, 0x65, 0xd9, 0x94, 0xaa, 0xc0, 0x5b, 0xba, 0xc0, 0x69, 0x15, 0xa0,
	0x0d, 0x22, 0xfc, 0x63, 0xc1, 0xa0, 0x76, 0x92, 0x11, 0xec, 0x94, 0xee, 0x37, 0x5a, 0xb4, 0xd6,
	0x36, 0x0e, 0xb3, 0xd7, 0x0e, 0x3b, 0x04, 0x4f, 0x48, 0x56, 0x48, 0x63, 0x50, 0xb4, 0xa3, 0x67,
	0x96, 0x9c, 0xde, 0x59, 0x0a, 0xc1, 0x11, 0x12, 0x79, 0xfd, 0x23, 0x0f, 0xcd, 0x89, 0x45, 0x4e,
	0x55, 0x2c, 0xfc, 0x0c, 0x4e, 0x69, 0x6d, 0xba, 0x5e, 0x74, 0x16, 0xf6, 0xff, 0xb3, 0xe8, 0x9d,
	0xe8, 0xf2, 0xca, 0xfc, 0xc0, 0xe7, 0x37, 0x72, 0x65, 0x26, 0xe0, 0x3d, 0xc7, 0x14, 0x6f, 0xe2,
	0x28, 0x17, 0x1c, 0x8a, 0x82, 0x8f, 0x7f, 0x59, 0x30, 0x78, 0xb9, 0xe4, 0x29, 0xcb, 0x24, 0x79,
	0x00, 0x6e, 0xf5, 0x38, 0x10, 0x73, 0xf8, 0x9b, 0xe7, 0x62, 0x34, 0x34, 0x7f, 0x36, 0xc1, 0x4b,
	0x78, 0x25, 0x8c, 0x09, 0x6f, 0xa5, 0xea, 0x83, 0x57, 0xc5, 0x99, 0xf0, 0xb6, 0xdc, 0x2e, 0x7c,
	0xe6, 0xaa, 0xa7, 0xeb, 0xfc, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb2, 0x5e, 0x3a, 0x13, 0xd6,
	0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ImplantClient is the client API for Implant service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ImplantClient interface {
	Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*Resp, error)
	Update(ctx context.Context, in *UpdateReq, opts ...grpc.CallOption) (*Resp, error)
	Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*Resp, error)
}

type implantClient struct {
	cc *grpc.ClientConn
}

func NewImplantClient(cc *grpc.ClientConn) ImplantClient {
	return &implantClient{cc}
}

func (c *implantClient) Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/v1alpha1.Implant/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *implantClient) Update(ctx context.Context, in *UpdateReq, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/v1alpha1.Implant/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *implantClient) Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/v1alpha1.Implant/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImplantServer is the server API for Implant service.
type ImplantServer interface {
	Create(context.Context, *CreateReq) (*Resp, error)
	Update(context.Context, *UpdateReq) (*Resp, error)
	Delete(context.Context, *DeleteReq) (*Resp, error)
}

// UnimplementedImplantServer can be embedded to have forward compatible implementations.
type UnimplementedImplantServer struct {
}

func (*UnimplementedImplantServer) Create(ctx context.Context, req *CreateReq) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedImplantServer) Update(ctx context.Context, req *UpdateReq) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedImplantServer) Delete(ctx context.Context, req *DeleteReq) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterImplantServer(s *grpc.Server, srv ImplantServer) {
	s.RegisterService(&_Implant_serviceDesc, srv)
}

func _Implant_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImplantServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1alpha1.Implant/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImplantServer).Create(ctx, req.(*CreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Implant_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImplantServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1alpha1.Implant/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImplantServer).Update(ctx, req.(*UpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Implant_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImplantServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1alpha1.Implant/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImplantServer).Delete(ctx, req.(*DeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Implant_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1alpha1.Implant",
	HandlerType: (*ImplantServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Implant_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Implant_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Implant_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1alpha1/api.proto",
}
